### PR TITLE
publish the website

### PR DESCRIPTION
**Pull request by huahang**
Try to publish the website according to:
https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

### CODE REVIEW

**Comment by davids5** [comment]
@xiaoxiang781216 - not my area of expertise.

**Comment by Ouss4** [comment]
As far as publishing the website, the change looks good.

**Comment by btashton** [comment]
I'll take a look tonight, but this does not look right to me. If we are manually generating the site branch content then I would think it should only be the static content, none of the other stuff, but I want to make sure I understand it from the Apache side.

**Comment by btashton** [comment]
@huahang Sorry it took me so long to get back.  So I think this is OK for now, effectively running the "build" on your machine and then committing to this branch.

What I would say is we really should make this an orphan branch which is not connected to master since is has no history related to master.  This is what you would normally do for something like github pages. What I would suggest we do here is create the branch with an empty file manually, and then open the PR against the branch with the static content.

I also have some content changes I would like to see, but we can handle that as separate PRs.

**Comment by btashton** [comment]
Also there is a nice little script on this apache project for generating the site and commiting it to the right branch.  Maybe we can pull that in, just so there is no confusion about how the content is generated?

**Comment by justinmclean** [comment]
Hi,
> What I would say is we really should make this an orphan branch which is not connected to master since is has no history related to master.
> 
We can put it in it own repo if you want, we can have an many as we need.

Thanks,
Justin

**Comment by btashton** [comment]
@justinmclean I don't think there is any real need to do that.  Keeping the branch in the same repo makes things cleaner for linking as is done with that script I linked to.

**Comment by btashton** [comment]
@huahang What do you think about using this to generate the PR against the asf-site branch for a release?  I also have an example of what I am talking about with the orphan branch as asf-site in my fork as well.

**Comment by huahang** [comment]
@btashton The `publish.sh` script looks cool! :-) I think the orphan branch makes sense. But it seems that Github won't allow a PR from an orphan branch against the current `asf-site` branch since they don't have a common ancestor. Is it possible to do a git push -f? I don't know. I don't have write access to this repo. >_<

**Comment by xiaoxiang781216** [comment]
Let's me delete and recreate asf-site as an empty branch?

**Pull request closed without merging**
