### PR TITLE
CI: Add documentation on triggering the deployment workflow

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Add documentation to the README on triggering the deployment workflow.

### CODE REVIEW

**Comment by btashton** [comment]
@adamfeuer @v01d @Ouss4 since you all have been helping out with the documentation I figured I should point you at this and add it to the README.

**Comment by adamfeuer** [comment]
Thanks @btashton – this is what we run to deploy the website, including documentation, is that right?

**Comment by btashton** [comment]
yeah eventually this trigger will get called from the OS CI, but we need secrets configured for that and INFRA was looking into it so it is a quick manual step for now.

**Comment by adamfeuer** [comment]
@btashton Cool, thank you. LGTM. 👍

**Comment by v01d** [comment]
> yeah eventually this trigger will get called from the OS CI, but we need secrets configured for that and INFRA was looking into it so it is a quick manual step for now.
> 
> If the PR is against this repo then no additional action is needed.

Is there a link you can share to the request to INFRA? I would like to ping them to have this sorted out.

**Comment by v01d** [comment]
@btashton sorry to bother you, not sure if you were notified about my last comment

**Comment by btashton** [comment]
@v01d sure https://issues.apache.org/jira/browse/INFRA-20805  it was originally just about the PAT for deploying our container images to GitHub Container Registry, but it has the same PAT secret issue.  They said they needed to look into this, but I added a comment just not about this other use case explicitly.

**Comment by v01d** [comment]
Cool, thanks. I see you also just pinged them.

**Comment by v01d** [comment]
@btashton we're still not getting response from INFRA on this, which is worrying. Also, is it your intention that they create a PAT for us and then add it as a secret or the PAT would be from one of us?

**Comment by btashton** [comment]
> @btashton we're still not getting response from INFRA on this, which is worrying. Also, is it your intention that they create a PAT for us and then add it as a secret or the PAT would be from one of us?

My intention is they create one because otherwise the PAT will include our private repos due to scoping. I can more it back to waiting for infra from review so it goes to the top of the  queue. 

In the meantime we can also wire up a job that run every couple hours that syncs if there has been a change. Then it is automatic, and we still have the manual button if needed.

**Comment by v01d** [comment]
That's a good idea

**Comment by btashton** [comment]
@v01d do you want to give it a go? Otherwise I could pick it up over the weekend since I don't think there is a huge rush.

I'm thinking we just kick the build every two hour and don't worry about inspecting the commits in OS for changes since changes in some markdown external to the doc would also require a new build. It's not like these commits are that big and we could always prune the asf-site branch if needed.

**Comment by v01d** [comment]
Sure, I can give it a try. I assume GH actions supports a cron job, right? I will open an issue for this.

**Comment by btashton** [comment]
Yep you are looking for on.schedule

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

**Pull request merged**
