### PR TITLE
Add News and Announcements, with 9.0 news item

### PR DESCRIPTION
**Pull request by hartmannathan**
## Summary

I propose that the homepage of nuttx.apache.org should have a new
section called News and Announcements, that over time would contain a
list of the three or four most recent project-related news items.

Currently we have one news-worthy item: The release of 9.0.

## Impact

Please review and feel free to offer suggestions / improvements. Thanks!

## Testing

I tested the changes on my local host.

### CODE REVIEW

**Comment by btashton** [comment]
So there is actually some support for this already baked into the template.  Posts would go under `_posts`  (there is a dummy one there already).  And then you can render a feed with a collection of them as explained here
https://jekyllrb.com/docs/posts/

**Comment by hartmannathan** [comment]
Thanks. That sounds even better than hand-coding it. I'll study that. Meanwhile it looks like we have a second newsworthy item to put there (security announcement).

**Comment by btashton** [comment]
Great.  Thanks for doing this, the website has only been getting minimal attention, so getting some content would be really helpful.

**Comment by xiaoxiang781216** [comment]
Let close the stale PR.

**Pull request closed without merging**
