### PR TITLE
Initial checkin nuttx website github action workflow

### PR DESCRIPTION
**Pull request by liuguo09**
Nuttx website github action workflow:
1. Checkout nuttx website
2. Install essential tools
3. Run publish.sh and push asf-site branch

Signed-off-by: liuhaitao <liuhaitao@xiaomi.com>

### CODE REVIEW

**Comment by liuguo09** [comment]
One of the github action CI in my own fork as below:
https://github.com/liuguo09/incubator-nuttx-website/pull/8/checks

**Comment by liuguo09** [comment]
@btashton please help review again. Seems comments gone after I force pushed to update PR : (

To summarize:
1. I remove the additional sudo apt install bundle line you commented
2. Keep sudo ./publish.sh, or it would fail as below:
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
##[error]Process completed with exit code 1.
More details in https://github.com/liuguo09/incubator-nuttx-website/pull/5/checks

**Comment by btashton** [comment]
I'll take another look. I run publish without sudo locally and everything ends up in the working directory. I'll fork it and take a look at what's up.

**Comment by btashton** [comment]
@liuguo09 Ok I finally got around to sorting out what what up using a ubuntu:18.04 container which I think is close to the github environment.  I installed the system packages that you have and then before calling publish I create a local GEM_HOME and exporting the bin path in it so the bundler application is available.
```
export GEM_HOME=$HOME/.gem
export PATH=$PATH:$GEM_HOME/bin
```

**Comment by liuguo09** [comment]
@btashton You are right. I update with the export cmds you provide before calling publish.sh and it works. As below,
https://github.com/liuguo09/incubator-nuttx-website/blob/master/.github/workflows/main.yml
But it must come with a git author email and name before git push asf-site. Now I hard coded with my own info. But I think it would be better to use some official or fake email/name instead. What's your idea?

**Comment by btashton** [comment]
for the author and email, prior to running `publish.sh` we can get them like this:
```
username=`git log -1 --pretty=format:'%an'`
email=`git log -1 --pretty=format:'%ae'`
```

**Comment by liuguo09** [comment]
> for the author and email, prior to running `publish.sh` we can get them like this:
> 
> ```
> username=`git log -1 --pretty=format:'%an'`
> email=`git log -1 --pretty=format:'%ae'`
> ```

Good idea! Update done, please take a look.

**Pull request merged**
