### PR TITLE
Create release page for 9.0.0

### PR DESCRIPTION
**Pull request by btashton**
This adds the first Apache release to our release page.  A screen shot of it can be seen here:
new_release

### CODE REVIEW

**Comment by btashton** [comment]
@patacongo @xiaoxiang781216 @liuguo09 If one of you might be able to take a look at this that would be great.  I attached the screen shot from the build so that you can preview it.  The release has been mirrored now, so I would like to announce it today, but need the website updated with this first.

**Comment by xiaoxiang781216** [comment]
Looks great! Thanks you and @Ouss4 hardwork to make this happen.

**Comment by xiaoxiang781216** [comment]
Should the version number be 9.0.2? Anyway, we can fix this in the next release.

**Comment by btashton** [comment]
> Should the version number be 9.0.2? Anyway, we can fix this in the next release.

It is 9.0.0, the RC number  is not part of the actual release version. We can discuss changing an making patch be the RC number but that is not inline with what the other projects are doing in the incubator. (I don't have a strong opinion).  They create RC against the same version until it passes the release process. Then when there is a bug fix the bump the patch and create more RC until it is released.

**Comment by xiaoxiang781216** [comment]
Anyway, let's dissucss the detailed in the next release.

**Comment by xiaoxiang781216** [comment]
@btashton but where can I find the download link from our website?

**Comment by liuguo09** [comment]
@btashton  Looks great. 
@xiaoxiang781216 In home page click "Get NuttX" , then it link to download page https://nuttx.apache.org/download/

**Comment by xiaoxiang781216** [comment]
Got it. I remember it jump to github before?

**Pull request merged**
