### PR TITLE
Create release notes for all past releases

### PR DESCRIPTION
**Pull request by btashton**
This is a work-in-progress to get the old release information on the site and prepare for a first Apache release.

- [X] Generate release pages for pre-Apache releases
- [x] Add disclaimer about past releases
- [x] Generate links to release pages

### CODE REVIEW

**Comment by patacongo** [comment]
ReleaseNotes for all releases (with typo fixes) is in the top-level ReleasNotes file in the NuttX repoxitory.

I also have all 133 release tarballs and ReleaseNotes if you want them.

**Comment by btashton** [comment]
I guess up to you if you want to have those included. They would just need to be uploaded to the bitbucket download space.  The script I wrote will generate the markdown files.

The high level release file will pick these up using the metadata in the header I added. I'll get back to this towards the end of the week.

**Comment by btashton** [comment]
Download page looks something like this for now.  Once release pages are created for Apache releases a table will appear for Apache with links to SHA256 and ASC files.
image
@patacongo Greg do you think you could upload sha256 files for the bitbucket releases?
They look like this. I have also attached a zip with all of the `.sha256` files here
[nuttx-sha256.zip](https://github.com/apache/incubator-nuttx-website/files/4105187/nuttx-sha256.zip)
```
Generating SHA256s for 7.13
OS: 073236d1452922231e7aec5bdb908a96b4ee0fb4a75760fa06cd9204ecd649c3
Apps: 3f1b9ad1504ccce33c7043ba71cc454e4475b98af818dd764c85ededbdbddae9
Generating SHA256s for 7.14
OS: d692cc84667a9dca6c3fd6886e45ac6afa82e8a7871e6f3fddd43d12d352a6fa
Apps: 979e6df21c8995d3f6b538bc1b0398ec9943e9edb36a499d6392c22472189a27
Generating SHA256s for 7.15
OS: 2580248932fe044494bc87778dbcb887c28a68f42961083e1901e9864def876d
Apps: d935735f492bd60bc7b71c1879b96640d801c7b7068f47486fb8be1fac55ec15
Generating SHA256s for 7.16
OS: 270f2f12baa2a1545391c55a44e1b7a4a5e1a8af03242826d6a84111c520fe26
Apps: 2c6c39f05c414acaad917a302db85548ae217fa69f01c5da1084d052e6479c02
Generating SHA256s for 7.17
OS: 75a17e815f0280b06cfef60d0cba3edf48da30e9309170e91c5160229c879a31
Apps: 14c3ca5c8185cdf6af063bbe7bf68bb2289c716174ac5e82166953a70d88cafd
Generating SHA256s for 7.18
OS: 9f0c5c7c860a92e3962c43af7d74f796794d6da2145caa46debb9813dc911d3d
Apps: bd76a8e1934fdeab09171240c166035e4d0d8670952be53ff9f33dfd3dab7565
Generating SHA256s for 7.19
OS: b5e581ee9a43a27bea3cb2bc13ee911a47af099a2516978074c43184f282c6ac
Apps: 61e2d56852e35c0f3dc83073e778b8cd29a51d8e75fef7349a2e66a470533b6e
Generating SHA256s for 7.20
OS: 3815c54d4b8a2bd6bb4dc1fae85a78c4571fe585f240140eb08e510c81b9874f
Apps: 5d672b8d2226ab7fb8f69faae52330a5f76a7aa3228d1086b2552b166757032e
Generating SHA256s for 7.21
OS: 85fef03536256679149a24833d3c56441893813b65cc840e7087f062ba3bded0
Apps: a38de8671a4acc92850e8bb4c8666f29ce1dd20fa068a5c8ac84b23f19bf50e3
Generating SHA256s for 7.22
OS: af5fc19a8775cf680d41c57462e0a48467e37f51fb1de1bf0a1a89f41b00644c
Apps: eb68f04391f7de14d7dd7b748268cae2f4d6f6e75c5f65f3855638206c2bed83
Generating SHA256s for 7.23
OS: 2f0f95ee814c84e154da65d51be5e7e4ce7cff79ea4060e802d12d5ff93cb301
Apps: ea51f316c7eb32cc063320f7dba143e8c6d8d54e8c9e277fa9d16ed5b056fb88
Generating SHA256s for 7.24
OS: d9f657d3e98020675817e6da238c1c25d319c88601176d5d6079bc344d6ea238
Apps: fb5c90defda7f0c5b04f72ab94f302bdcc918f1028e272aa5f0c7a334f6b15ec
Generating SHA256s for 7.25
OS: 87d7ab5d7106f757371c79b06e77653b81da1c84dc1d8ea2e990917922f02eff
Apps: d96fdcc4cdf585091cf7be1a499c14ca419d33ac68b96011db89c468ab3d265f
Generating SHA256s for 7.26
OS: 5a77ee469670c921203a3db7789cbde03354d64fbadfc2b03aa236564dd3353d
Apps: 0699a4f7a8e4b075e7d0a3a8e70c7f41c660bd802c621709b7c03402b6ab9395
Generating SHA256s for 7.27
OS: 4437857769a6d1de58817a27dce9c870f361dd979cdfa9ffac9eac08d7095a85
Apps: d7a85a936b38e0e6b61ac97fcba07ccde9a7b1f3a2cdad5be4106918b98fa969
Generating SHA256s for 7.28
OS: 9c3ab91bb2df190d54b7426d0758c354745ef649a5a972e2b0d172a37cf95a72
Apps: 4667113706774042f9d6bd794b3957700cabc3ec5ffc7a1113e150c1f0caa4ae
Generating SHA256s for 7.29
OS: cc7bf08ea5ee24f85a7abacb36134b1f9303a817b14fb817a45c2924eac449ba
Apps: 36960d995314e6a45b6b5c379be81034a1d99bd535fe59f457d3ae5fa7f443d9
Generating SHA256s for 7.30
OS: cf6530e676b69716bab15bf3cdff6dc2c60960eaa2061992de948cde5487dfca
Apps: 02978f7a04bcb3e1a9e5bf3673a43d26082ded12b5676b92a1bc465f4a86b4f5
Generating SHA256s for 7.31
OS: ce0db43315cf1c19cb051385677fe73c9509c6c2bae0e5fd6d405a89ccf5a3f4
Apps: 28903932a5d08f98f40b58f3a47132d623442c231b8617da23e4e1af1ba9899c
Generating SHA256s for 8.1
OS: 1e1b7e548fc22905c2819dcc97657f345c8aafa7952ee41c333ef9122f1ade37
Apps: 5dcae9ebc80254ad03ca5d7e3cfbb3a48e394a81c1873138a6e168c51b348a46
Generating SHA256s for 8.2
OS: 85d7fd421a8e1e377b29dd942055e9aeb76250dc4fcb81736f3068180ea4f621
Apps: 426c59795f6c2beae4ab48f91d47ee94c0695e568031a3df81faeede9f8ae332

$ sha256sum *.sha256 --check
apps-7.13.tar.gz: OK
apps-7.14.tar.gz: OK
apps-7.15.tar.gz: OK
apps-7.16.tar.gz: OK
apps-7.17.tar.gz: OK
apps-7.18.tar.gz: OK
apps-7.19.tar.gz: OK
apps-7.20.tar.gz: OK
apps-7.21.tar.gz: OK
apps-7.22.tar.gz: OK
apps-7.23.tar.gz: OK
apps-7.24.tar.gz: OK
apps-7.25.tar.gz: OK
apps-7.26.tar.gz: OK
apps-7.27.tar.gz: OK
apps-7.28.tar.gz: OK
apps-7.29.tar.gz: OK
apps-7.30.tar.gz: OK
apps-7.31.tar.gz: OK
apps-8.1.tar.gz: OK
apps-8.2.tar.gz: OK
nuttx-7.13.tar.gz: OK
nuttx-7.14.tar.gz: OK
nuttx-7.15.tar.gz: OK
nuttx-7.16.tar.gz: OK
nuttx-7.17.tar.gz: OK
nuttx-7.18.tar.gz: OK
nuttx-7.19.tar.gz: OK
nuttx-7.20.tar.gz: OK
nuttx-7.21.tar.gz: OK
nuttx-7.22.tar.gz: OK
nuttx-7.23.tar.gz: OK
nuttx-7.24.tar.gz: OK
nuttx-7.25.tar.gz: OK
nuttx-7.26.tar.gz: OK
nuttx-7.27.tar.gz: OK
nuttx-7.28.tar.gz: OK
nuttx-7.29.tar.gz: OK
nuttx-7.30.tar.gz: OK
nuttx-7.31.tar.gz: OK
nuttx-8.1.tar.gz: OK
nuttx-8.2.tar.gz: OK
```

**Comment by btashton** [comment]
@patacongo I would like to get this bit of the webpage released if that screenshot looks good enough. The SHA bit would be nice to have but I don't think blocks this.

**Comment by patacongo** [comment]
Hi, Brennan,

Yes, I can do that.  I am probably not the best person for any web stuff since I don't really have the competence.  Do you still need SHA1's?  I can send them but the should all be README ReleaseNotes for each release.  I will double check them before merging.

**Comment by patacongo** [comment]
Sorry.  Those are SHA1 sums in the ReleaseNotes.  I get these going back to the original tarballs:

<pre>
$ sha256sum *-7.*.tar.gz
cdf6468f016f0d449d4490ffc0b5f44d70e9b0fe821322e8ed662cdc31457f48 *apps-7.1.tar.gz
e7dac30f9c0be80eda98a2097c6a1e02a9b807e4afe02a745848b9510e1a25c5 *apps-7.10.tar.gz
11e31b1afcc72834ae4e988d2e3ac967f224505643dbbe3fda35dd08d1ec6d58 *apps-7.11.tar.gz
0f59f3db77339b6bc0810481b7bc147705280d0a693d470250373122676f4804 *apps-7.12.tar.gz
c99ea0645ac367b90d5cd7921246c68991dad738eee758f4be3ab7e4e9b99f6c *apps-7.13.tar.gz
f89add67b3dfad6e4e16812ef0c459a3e1a2728328a0906ee3c71e248c281035 *apps-7.14.tar.gz
bcc8e2edc4f6dfb51e856c80ad9b79801afeb659e49a6f60a7f838b6baecbb4b *apps-7.15.tar.gz
cdcb1f2e0250238ffefd6f7defa17771e4493cd1748fa1894b8017084ee8f879 *apps-7.16.tar.gz
6707014eb4dc8b214c2b5b3ee6395e7ffaed2a4556476a49fe6d6ef0334de8ac *apps-7.17.tar.gz
8d47a854ead883f1a61e892db4589bb10a738116519354b8078813bda39b82d5 *apps-7.18.tar.gz
627a8a6d5f055b523d40b3db615ba2bc05f6d227372bde957b9e6cafa75ae6f8 *apps-7.19.tar.gz
2086e51bda5c0c47fd930e9823544d78ed0920d891943d61a7984ef02d61faa1 *apps-7.2.tar.gz
c39fdfc5110f9742d5f62eff25829882e4df710fd3c5a807e90adb9b4b4fb614 *apps-7.20.tar.gz
3ee0404685e361757ce0df38b4c51398899440c464bee56af943105ae1f045c0 *apps-7.21.tar.gz
7c40bc551d46fac7a74e92d706de0f667374afa550fd7cb68ded59352e013884 *apps-7.22.tar.gz
ba4cb4a3c25594fd1bae981ace76fe00e06bf992ecdf0013e6b66b171dd4d589 *apps-7.23.tar.gz
2babe5c4e6783d86ac4153c0efacaa031c150b1f4b211512e0d2b7067984a207 *apps-7.24.tar.gz
eeb0d90eeffeb2387d12e01746c5bb55ed1c75043e39ff8f96d8768ebe4e0123 *apps-7.25.tar.gz
8c5de9d856d59196da86ddc15bf6cb185035f2189f116d98c019c5d3f66629c0 *apps-7.26.tar.gz
06799c2d96fa155af2cd70cf78bfe71f7ce02ebd12cde7b2c11edef71ebec816 *apps-7.27.tar.gz
8325b36bbe992474ddcb7bb965804ce45d7959ef18fefa35c3c9948089ec9fc5 *apps-7.28.tar.gz
d42ae57f903f6d52db6f634ddc4e768f4cc497b456aa46eb5201a7fa00956226 *apps-7.29.tar.gz
cf1d477591046e531e676b916d283e1feae360303208654fed4113a0b6c23cf8 *apps-7.3.tar.gz
bec667837e544590aae2262916210634b6126970fbc5cafb498476cbbdac2dc3 *apps-7.30.tar.gz
cbe53d3b9b6b950e456fda1c7c3190ea3f6cb57d381b7cb7c4917ad5d1fe67b0 *apps-7.31.tar.gz
c65d0d14e52e9f7b9125aea062ea2428b2606684ef294264f9a247579410f750 *apps-7.4.tar.gz
048f98a9bcd51866c38d8f66b56022faa8d54d27c6dc383ca94ec9e52f6684d9 *apps-7.5.tar.gz
3640b65ec69727d7ddc00b49fdc31c44cf0476b063889d6fd0ff5e37ff6a6e74 *apps-7.6.tar.gz
2f1a5bddee89bb6e745f7f39fb7ad8624c8dc159b92e55f64356ec8d28c70870 *apps-7.7.tar.gz
2e3ea0adaf0d0fa88329db97062549d422e256afeb3edca90d5eae730d9403c6 *apps-7.8.tar.gz
039988d18a27915455b5b4d47b8007b441971ade8cd41c7a8501f7f085a5a4a1 *apps-7.9.tar.gz
7b0a6cc6decdb239b606b77b4962fff49145da9c2698f7b14e0489509fc7dc89 *nuttx-7.1.tar.gz
756fb268e8d884accd34d738d206395304a04d20392d8f71190fe78297ddf28f *nuttx-7.10.tar.gz
ea74d7e85a192fc5323c5f5d3b2cfb9e8aaa51d378c92630b9ec5dfc7c6da506 *nuttx-7.11.tar.gz
1d8af0cdcaac4fd04e61b2d01977adc76d0974882bdb94f7d838dceb86e36050 *nuttx-7.12.tar.gz
1c4b49daf2360570b9e6e72515cd3a4aaae0c0797dfcf335991293670fef61ef *nuttx-7.13.tar.gz
f5eba4ecee9b459a6159b156fb3c88f5a72fbc8316c80b8fb61c148f654d33f0 *nuttx-7.14.tar.gz
737bac6c40960d7dc11af10601332ade90dd55ddc4b022c241ae86abdb9bbf2d *nuttx-7.15.tar.gz
181a03dce391c8abe7f2d538808b60114d5c58e514977a7bd642bf32ce4a77e4 *nuttx-7.16.tar.gz
21926184477cef54072c8c21c817a87f59fc36d082ae5b4ae77a02638b98964d *nuttx-7.17.tar.gz
cb5f9319217762fffe08d851b88cc3085b53234a44535b79445d764014ec7e9d *nuttx-7.18.tar.gz
7cfeb11e24f765e014d045aa46ab1c205863f844b625721c88bfd20da70bc8a2 *nuttx-7.19.tar.gz
81aba3a305fe27ad55fea56651306533ea580fd37f62f29a551adf0de7a19d9f *nuttx-7.2.tar.gz
1322090f88817da6827db72e85337770344480283035afbe0784f339f771880c *nuttx-7.20.tar.gz
28e281112bfa470075b134f5623dd062d625ccd99f4df193534902cfa06b7644 *nuttx-7.21.tar.gz
82c633b56bf1b925880d4bbc83f400283415ff6ae7a60f179afe242a496faba6 *nuttx-7.22.tar.gz
9254a8f82b311a0d76611494027665426b1c5c8fc771e651d47a93d42eb15e62 *nuttx-7.23.tar.gz
6975c98b2d27e8de46cf7493ebf811c1bfaa26c3fd91c4f4fdbd7219d7b1f8ff *nuttx-7.24.tar.gz
6bd97321b2c7dcec46c7fb21c29f2daa6269cc81b413c49b906676854223d88a *nuttx-7.25.tar.gz
4682b599ea72205ebe8cee1e229ba0db80684bfceddfed4a41e4728cea336b98 *nuttx-7.26.tar.gz
46d89f2795f5e8cb78fdad2b7535d7f7257db8427810f5721758e4589b897809 *nuttx-7.27.tar.gz
92fde612a542c47d11eb0bd85dc1d53ccf236f8106ad6b216fdfbc77f3b8ce1d *nuttx-7.28.tar.gz
c8b6e83c7d30449306113dbd936340ec4422bc87b5dde8b06a7d0db3b79bb19f *nuttx-7.29.tar.gz
b729081f4ebcc65ef5f4223cd7baedcfe22924a5a4d4c8f719fd50fb06683ede *nuttx-7.3.tar.gz
10a2b9b659ed5e330da201aae7535a7c780308875de73546d501ec026dbce704 *nuttx-7.30.tar.gz
a17ad8e64c6be08a9a0e10ba9488ed7a1f65bc9075dea910a31e313c85733c5d *nuttx-7.31.tar.gz
39302beaa2d8a7a233d56c2219c67e867f0941169fa0775960f36a927bea307c *nuttx-7.4.tar.gz
681fb42b7ddb9ebb458ed8b6ac9ca5706578077c544ad959b6dd3c76177cb442 *nuttx-7.5.tar.gz
15f0936dac5abbbdcaf392db9b05001007e246a5f05409928090df0811ea23b1 *nuttx-7.6.tar.gz
ff25b1ebdcf082991ae91d4998be42987b598d2302dcbaa91d425892fcedd84e *nuttx-7.7.tar.gz
e6d7047bbf65d3f159c86400916bd29a303c534815881064cd036e0ab5b11e26 *nuttx-7.8.tar.gz
a6bb212747aba3e342c5f6b3841137d41663d485e2378ef0a3784c0acbfaa899 *nuttx-7.9.tar.gz

$ sha256sum *-8.*.tar.gz
faf890f6fb16ae5755ab48c11416dfec908bacb8db6d30b7eae22204889b365c *apps-8.1.tar.gz
723a0c73aa6449c0403ded8ceedf58a4395710c8541562f2b35fad97a9846d0f *apps-8.2.tar.gz
20cd662d13de14758318898e6eda08c688c261b111f82e38ee231fd0ef9af6c4 *nuttx-8.1.tar.gz
c361c9e5e133c7b678071678b23aa0dd463ffd48b63a10203bc13189f788afbf *nuttx-8.2.tar.gz
</pre>

**Comment by patacongo** [comment]
I am really not comfortable merging web stuff as I discussed above.  I don't know what I am looking at, but since it has been open for 7 days, it probably should be committed.

**Comment by btashton** [comment]
Greg no problem. We will figure out some other people to help with these that are more web knowledgeable, I just wanted to get the site reflecting the correct information as we get ready for a release. (I want to get back to finishing my OS code sitting in a branch for too long...) 

About the SHA I was asking if we could upload the SHA256 files to the bitbucket download page as I included in the attached zip to my previous comment.  The advantage is that these will be generated for the Apache releases and it would be nice to have a link to them in the table as well for people to easily check there downloads.  I put this as low priority since it never existed before and the information can be found by looking in the readme files.

**Comment by patacongo** [comment]
Okay, I uploaded all of your SHA256 files.  I didn't understand that that is what you wanted me to do.

**Pull request merged**
